### ISSUE TITLE
Cannot get AccountDTO via client.get_user(puuid)

### ISSUE THREAD

**Issue by neilsorkin19** [frissyn/valorant.py#34]
Getting an AccountDTO by name and tagline works (```client.get_user_by_name(gameName#tagline)```), but getting an AccountDTO by puuid (```client.get_user()```)does not work.

Example using ```SEN ShahZam#huh```:
```client.get_user("ZEwGdkv9sZL2pgwPUfEG-SnldEtqwaqW-neW8y7HL2jmdNptEKpgD598uUA-K7CUR-j67ktFdqJNhg") # SEN ShahZam, does not work```
```client.get_user_by_name("SEN ShahZam#huh") # does work```

**Comment by frissyn** [comment]
Thanks for reporting!

After reproducing this, I've found the issue. When `Client.get_user_by_name` is called, the client builds a URL pointing to the Riot Games from the parameters and makes a request to it.

The API endpoint for Riot Accounts uses `routes` rather than `regions`, and the URL builder was using the wrong value. That returns a 400 reponse, and the client interprets it to be missing, and gives you `None`.

**Expected Behavior:**

```py
client = valorant.Client(KEY, region="na", route="americas")
client.get_user("puuid") # Should build => https://americas.api.riotgames.com/riot/account/v1/accounts/by-puuid/puuid
```

**Actual Behavior:**
```py
client = valorant.Client(KEY, region="na", route="americas")
client.get_user("puuid") # Wrong URL => https://na.api.riotgames.com/riot/account/v1/accounts/by-puuid/puuid
```

I've added this bug to the [`v1.0.3`](https://github.com/frissyn/valorant.py/milestone/3) milestone, which will go live in a few days. Please use `.get_user_by_name` until then.
